---
title: "HEATMAP"
output: html_notebook
---

## Creating three seperate heatmaps for infected, bystander and naive

```{r}
binary <- readRDS("int/4.1_binaryRegulonActivity.Rds")
dim(binary)
binary_NonDupl <- readRDS("int/4.2_binaryRegulonActivity_nonDupl.Rds")
dim(binary_NonDupl)
selection <- readRDS("int/4.3_regulonSelections.Rds")
selection_corr <- selection$corr
length(selection_corr)
```

```{r}
selection_corr <- binary_NonDupl[selection_corr, ]
selection_corr <- as.data.frame(selection_corr)
dim(selection_corr)
```

```{r}
cells <- colnames(selection_corr)
Sample <- gsub("[[:upper:]]","", cells)
Sample <- gsub("\\.", "", Sample)
Sample <- gsub("1", "naive", Sample)
Sample <- gsub("2", "bystander", Sample)
Sample <- gsub("3", "infected", Sample)
Sample <- gsub("4", "naive", Sample)
Sample <- gsub("5", "bystander", Sample)
Sample <- gsub("6", "infected", Sample)
Sample <- factor(Sample)
```

```{r}
DataSet <- gsub("[[:upper:]]","", cells)
DataSet <- gsub("\\.", "", DataSet)
DataSet <- gsub("1", "ExpSecond", DataSet)
DataSet <- gsub("2", "ExpSecond", DataSet)
DataSet <- gsub("3", "ExpSecond", DataSet)
DataSet <- gsub("4", "ExpFirst", DataSet)
DataSet <- gsub("5", "ExpFirst", DataSet)
DataSet <- gsub("6", "ExpFirst", DataSet)
DataSet <- factor(DataSet)
```

```{r}
pdata <- data.frame(cells, Sample, DataSet)
```


```{r}
library(ComplexHeatmap)
colors = structure(c("black", "white"), names = c("1", "0"))
WholeHeatMap <- Heatmap(selection_corr, col = colors, cluster_rows = TRUE, cluster_columns = TRUE, name = "legend", show_column_names = FALSE)
WholeHeatMap
```

```{r}
t <- row_order(WholeHeatMap)
t <- as.data.frame(t)
t <- t$c.36L..27L..9L..53L..6L..21L..34L..51L..22L..66L..61L..44L..41L..
row <- rownames(selection_corr)

order <- c(1:68)
for (i in order) {
  z <- t[i]
  order[i] <- row[z]
}

order <- rev(order)
```


### Infected

###############################################################################
### retrieving the percentage of virus in each cell
```{r}
#subsetting the cells
load("/home/ehsan/Desktop/Sibylle/Sibylle/E8E9E10B9B10B11/E8E9E10B9B10B11Analysed.Robj")
#TSNEPlot(object = E8E9E10B9B10B11)
E8E9E10B9B10B11sub <- SubsetData(E8E9E10B9B10B11, ident.use = c(1,2,3,10,7,9))
#TSNEPlot(object = E8E9E10B9B10B11sub)
#dim(as.matrix(E8E9E10B9B10B11sub@data))
cells <- colnames(as.matrix(E8E9E10B9B10B11sub@data))

#DATA_DIR <- "/home/ehsan/Desktop/Sibylle/SibylleData/E8E9E10B9B10B11/filtered_gene_bc_matrices_mex/dualHuman"
#E8E9E10B9B10B11.data <- Read10X(data.dir = DATA_DIR)
#E8E9E10B9B10B11 <- CreateSeuratObject(raw.data = E8E9E10B9B10B11.data, project = "")
#RawTable <- as.matrix(E8E9E10B9B10B11@raw.data)
#RawTable <- RawTable[,cells]


data <- as.matrix(E8E9E10B9B10B11sub@data)
data <- exp(data) - 1
dim(data)
## Calculating total viral mRNA
virus <- data[18693:18704, ]
virus.tot <- as.data.frame(colSums(virus))
cell.tot <- as.data.frame(colSums(data))
cell.percent <- (virus.tot/cell.tot)*100
colnames(virus.tot) <- "Total_viral_mRNA"
colnames(cell.percent) <- "Virus_percentage"
t <- gsub("-", ".", rownames(cell.percent))
rownames(cell.percent) <- t


# cell.percent$Virus_percentage <- log(cell.percent$Virus_percentage + 1)
```


###############################################################################

```{r}
infected <- pdata[pdata$Sample == "infected", ]
dim(infected)
infMatrix <- selection_corr[order ,as.character(infected$cells)]
dim(infMatrix)
```

```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
#f <- as.character(infected$cells)
#cell.percent <- cell.percent[f,]
#############################
## Producing the annotation files
df = data.frame(infected$DataSet, infected$Sample)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown")))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix, col = colors, cluster_rows = FALSE, cluster_columns = TRUE, name = "legend", show_column_names = FALSE, top_annotation = ha)
print(InfHeatMap)
dev.off()
```

### bystander

##############################################################################


```{r}
bystander <- pdata[pdata$Sample == "bystander", ]
dim(bystander)
byMatrix <- selection_corr[ order,as.character(bystander$cells)]
dim(byMatrix)
```

```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
## Producing the annotation files
df = data.frame(bystander$DataSet, bystander$Sample)
ha = HeatmapAnnotation(df = df, col = list(bystander.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), bystander.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown")))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


png(file = "bystander.png", width = 544, height = 1080)
ByHeatMap <- Heatmap(byMatrix, col = colors, cluster_rows = FALSE, cluster_columns = TRUE, name = "legend", show_column_names = FALSE, show_row_names = FALSE ,top_annotation = ha)
print(ByHeatMap)
dev.off()
```

### Naive

```{r}
naive <- pdata[pdata$Sample == "naive", ]
dim(naive)
naiveMatrix <- selection_corr[ order,as.character(naive$cells)]
dim(naiveMatrix)
```

```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
## Producing the annotation files
df = data.frame(naive$DataSet, naive$Sample)
ha = HeatmapAnnotation(df = df, col = list(naive.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), naive.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown")))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


png(file = "naive.png", width = 562.5, height = 1080)
NaiveHeatMap <- Heatmap(naiveMatrix, col = colors, cluster_rows = FALSE, cluster_columns = TRUE, name = "legend", show_column_names = FALSE, show_row_names = FALSE , top_annotation = ha)
print(NaiveHeatMap)
dev.off()
```


### combining three heatmaps 

```{r}
class(InfHeatMap)
class(ByHeatMap)
class(NaiveHeatMap)
```

```{r}
NaiveHeatMap + ByHeatMap + InfHeatMap
```

### Infected heatmap with new criteria

```{r}
infected <- pdata[pdata$Sample == "infected", ]
dim(infected)
infMatrix <- selection_corr[order ,as.character(infected$cells)]
dim(infMatrix)
```

```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(infected$cells)
cell.percent2 <- cell.percent[f,]
#############################
## Producing the annotation files
df = data.frame(infected$DataSet, infected$Sample, cell.percent2)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent2 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix, col = colors, cluster_rows = FALSE, cluster_columns = TRUE, name = "legend", show_column_names = FALSE, top_annotation = ha)
print(InfHeatMap)
#dev.off()
```

########################################################
########################################################

```{r}
bystander <- pdata[pdata$Sample == "bystander", ]
dim(bystander)
infMatrix <- selection_corr[order ,as.character(bystander$cells)]
dim(infMatrix)
```

```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(bystander$cells)
cell.percent2 <- cell.percent[f,]
#############################
## Producing the annotation files
df = data.frame(bystander$DataSet, bystander$Sample, cell.percent2)
ha = HeatmapAnnotation(df = df, col = list(bystander.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), bystander.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent2 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "bystander.png", width = 434.5, height = 1080)
ByHeatMap <- Heatmap(infMatrix, col = colors, cluster_rows = FALSE, cluster_columns = TRUE, name = "legend", show_column_names = FALSE, show_row_names = FALSE, top_annotation = ha)
print(ByHeatMap)
#dev.off()
```

########################################################
########################################################

```{r}
NaiveHeatMap + ByHeatMap + InfHeatMap
```

### Ordering cells based on viral percentage

```{r}
infected <- pdata[pdata$Sample == "infected", ]
dim(infected)
infMatrix <- selection_corr[order ,as.character(infected$cells)]
dim(infMatrix)
```

```{r}
per <- cbind(cell.percent, rownames(cell.percent))
per <- per[colnames(infMatrix),]
per <- per[order(-per$Virus_percentage),] 
infMatrix <- infMatrix[,rownames(per)]
```

```{r}
rownames(infected) <- infected$cells
infected <- infected[rownames(per),]
```


```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(infected$cells)
cell.percent3 <- cell.percent[f,]
#############################
#Adding FoxJ1 to our analysis

############################
## Producing the annotation files
df = data.frame(infected$DataSet, infected$Sample, cell.percent3)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent3 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix, col = colors, cluster_rows = FALSE, cluster_columns = FALSE, name = "legend", show_column_names = FALSE, top_annotation = ha, row_title_gp = gpar(fontsize = 8))
print(InfHeatMap)
#dev.off()
```

```{r}
NaiveHeatMap + ByHeatMap + InfHeatMap
```

```{r}
png(file = "final1.png", width = 2048, height = 1080)
I <- NaiveHeatMap + ByHeatMap + InfHeatMap
print(I)
dev.off()
```

#################################################

# Retrieving the percentage numbers

```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(infected$cells)
cell.percent3 <- cell.percent[f,]
#############################
#Adding FoxJ1 to our analysis

############################
## Producing the annotation files
df = data.frame(infected$DataSet, infected$Sample, cell.percent3)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent3 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix, col = colors, cluster_rows = FALSE, cluster_columns = FALSE, name = "legend", show_column_names = FALSE, top_annotation = ha, row_title_gp = gpar(fontsize = 8))
print(InfHeatMap)
#dev.off()
```



```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(infected$cells)
cell.percent3 <- cell.percent[f,]

#########################################################
### Filtering data based on percentage
library(dplyr)
#adding one row to make things easier
# cell.percent <- cbind(cell.percent, rownames(cell.percent))

per <- cell.percent
per <- cbind(per, rownames(cell.percent))
per <- as.data.frame(per[f,])


per <- per[per$Virus_percentage > 0.5, ]

f <- as.character(rownames(per))
cell.percent3 <- cell.percent[f,]
#########################################################
#Adding FoxJ1 to our analysis

############################
## Producing the annotation files
df = data.frame(infected[f,]$DataSet, infected[f,]$Sample, cell.percent3)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent3 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix[,f], col = colors, cluster_rows = FALSE, cluster_columns = FALSE, name = "legend", show_column_names = FALSE, top_annotation = ha, row_title_gp = gpar(fontsize = 8))
print(InfHeatMap)
#dev.off()
```


```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(infected$cells)
cell.percent3 <- cell.percent[f,]

#########################################################
### Filtering data based on percentage
library(dplyr)
#adding one row to make things easier
# cell.percent <- cbind(cell.percent, rownames(cell.percent))

per <- cell.percent
per <- cbind(per, rownames(cell.percent))
per <- as.data.frame(per[f,])


per <- per[per$Virus_percentage > 4, ]

f <- as.character(rownames(per))
cell.percent3 <- cell.percent[f,]
#########################################################
#Adding FoxJ1 to our analysis

############################
## Producing the annotation files
df = data.frame(infected[f,]$DataSet, infected[f,]$Sample, cell.percent3)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent3 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix[,f], col = colors, cluster_rows = FALSE, cluster_columns = FALSE, name = "legend", show_column_names = FALSE, top_annotation = ha, row_title_gp = gpar(fontsize = 8))
print(InfHeatMap)
#dev.off()
```



```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(infected$cells)
cell.percent3 <- cell.percent[f,]

#########################################################
### Filtering data based on percentage
library(dplyr)
#adding one row to make things easier
# cell.percent <- cbind(cell.percent, rownames(cell.percent))

per <- cell.percent
per <- cbind(per, rownames(cell.percent))
per <- as.data.frame(per[f,])


per <- per[per$Virus_percentage > 14, ]

f <- as.character(rownames(per))
cell.percent3 <- cell.percent[f,]
#########################################################
#Adding FoxJ1 to our analysis

############################
## Producing the annotation files
df = data.frame(infected[f,]$DataSet, infected[f,]$Sample, cell.percent3)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent3 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix[,f], col = colors, cluster_rows = FALSE, cluster_columns = FALSE, name = "legend", show_column_names = FALSE, top_annotation = ha, row_title_gp = gpar(fontsize = 8))
print(InfHeatMap)
#dev.off()
```


```{r}
## producing the heatmap
library(ComplexHeatmap)
library(circlize) ## necessary for colour assignment
#############################
#Retrieving viral percentage information
f <- as.character(infected$cells)
cell.percent3 <- cell.percent[f,]

#########################################################
### Filtering data based on percentage
library(dplyr)
#adding one row to make things easier
# cell.percent <- cbind(cell.percent, rownames(cell.percent))

per <- cell.percent
per <- cbind(per, rownames(cell.percent))
per <- as.data.frame(per[f,])


per <- per[per$Virus_percentage > 30, ]

f <- as.character(rownames(per))
cell.percent3 <- cell.percent[f,]
#########################################################
#Adding FoxJ1 to our analysis

############################
## Producing the annotation files
df = data.frame(infected[f,]$DataSet, infected[f,]$Sample, cell.percent3)
ha = HeatmapAnnotation(df = df, col = list(infected.DataSet = c("ExpFirst" =  "red", "ExpSecond" = "blue"), infected.Sample = c("naive" =  "green", "bystander" = "steelblue4", "infected" = "brown"), cell.percent3 = colorRamp2(c(0, max(cell.percent2)), c("yellow", "red"))))

#############################
colors = structure(c("black", "white"), names = c("1", "0"))


#png(file = "Infected.png", width = 434.5, height = 1080)
InfHeatMap <- Heatmap(infMatrix[,f], col = colors, cluster_rows = FALSE, cluster_columns = FALSE, name = "legend", show_column_names = FALSE, top_annotation = ha, row_title_gp = gpar(fontsize = 8))
print(InfHeatMap)
#dev.off()
```



















